db: fix python3 crash on string to int conversion
Python3 requires a cast of options.sqlite_version to int, otherwise the following
crash happens:

  File "$HOME/Desktop/fdsa/quasselgrep-sqlite3_ts_ms/quasselgrep/query.py", line 145, in columns
    if self.options.sqlite_version >= 31:
TypeError: '>=' not supported between instances of 'str' and 'int'

Also raise an exception with an explicit error message in case quassel ever decides
to introduce characters in its schema version.